[package]
authors = ["Kevin King <4kevinking@gmail.com>"]
name = "ssh-wire"
version = "0.1.0"

[dependencies]
base64 = "*"
libc = "*"
rand = "*"
ring = { git = "https://github.com/kryptco/ring" }
serde = "*"
serde_codegen_internals = "*"
serde_derive = "*"
untrusted = "*"
byteorder = "*"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "sshwire"

[target.'cfg(target_os="android")'.dependencies.jni]
git = "https://github.com/prevoty/jni-rs"
default-features = false
